version: "2"
services:
    testmybot:
        build:
            context: ../../
            dockerfile: ./Dockerfile.testmybot
    testmybot-fbmock:
        environment:
            TESTMYBOT_FACEBOOK_WEBHOOKPORT: 3000
            TESTMYBOT_FACEBOOK_WEBHOOKPATH: "webhook"